### ISSUE TITLE
Ask about the implementation of plus-quic !

### ISSUE THREAD

**Issue by vanvantong** [mami-project/plus-quic-go#1]
Dear all administrators of plus-quic-go project,

I am a newbie about PLUS and QUIC. I want to ask you some questions about your project. Has your project completed?
If it completed, could you show me how to implement PLUS-enabled endpoint using QUIC?
Thank you in advance!

**Comment by FMNSSun** [comment]
The only thing that is different is that there's a config option `UsePLUS`:

```go
cfgServer := &quic.Config{
		TLSConfig: generateTLSConfig(),
        UsePLUS: true,
}
```

all the other stuff is unchanged. Have a look at the `example/` folder which has some examples (based on `lucas-clemente/quic-go`) but the only change is `UsePLUS: true` the rest remains unchanged. 

> Has your project completed?

No, as mentioned the mami-project is not yet completed and won't be for a couple of months.

**Comment by FMNSSun** [comment]
Bear in mind that you need to clone this as `lucas-clemente/quic-go` because it's a fork of it or add this as a different origin in your git config for `lucas-clemente/quic-go`.

**Comment by vanvantong** [comment]
Hi FMNSSun,

Do the client and server side need to install anything else to support?

**Comment by FMNSSun** [comment]
Not that I'm aware of. You just need to build it using the go compiler and then it works. However, this is not a network _stack_. There's no implementation of PLUS as part of OS network _stacks_ it's all just userspace implementation through UDP sockets and neither is QUIC part of OS network _stacks_ yet it's also just userspace implementation through UDP sockets.

**Comment by FMNSSun** [comment]
You can run an H2QUIC webserver with plus enabled and you should be able to visit it with a browser that supports QUIC (which currently I think is chrome only) or you can use an H2QUIC client. There's some example code on how to do that in the example folder (and the client is in https://github.com/mami-project/plus-quic-go/tree/master/example/client).

**Comment by vanvantong** [comment]
Thank you in advance!

**Comment by FMNSSun** [comment]
let's close this then.
